import Head from "next/head";
import Dashboard from "../components/Dashboard";
import AdminNavbar from "../components/NavbarComponents/AdminNavbar";
import Overview from "../components/LandingPageComponents/Overview";
import Stats from "../components/LandingPageComponents/Stats";
import RecentSales from "../components/LandingPageComponents/RecentSales";
import Footer from "../components/NavbarComponents/Footer";
import SideNavBar from "../components/NavbarComponents/SideNavBar";
import React from "react";
// import clientPromise from "@/connection";
import Login from "@/components/Login/Login";
export default function Home({ isConnected }) {

  const [showSideNavBar, setShowSideNavBar] = React.useState(true);

  return (
    <>
      <Head>
        <title>Dabzon Admin Dashboard</title>
        <meta
          name="description"
          content="Generated by Dabzon Admin Dashboard"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main bg-blue-50">
        <Login />

      </main>
    </>
  );
}

// export async function getServerSideProps(context) {
//   try {
//     await clientPromise;
//     const client = await clientPromise;
//     const db = client.db("myDatabase");
//     db.find({});

//     return {
//       props: { isConnected: true },
//     }
//   } catch (e) {
//     console.error(e)
//     return {
//       props: { isConnected: false },
//     }
//   }
// }
